version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: jenkins-agent-mq
    hostname: jenkins-agent-mq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq
    volumes:
      - ../data/rabbitmq/etc/:/etc/rabbitmq/mnesia/
      - ../data/rabbitmq/data/:/var/lib/rabbitmq/
      - ../logs/rabbitmq/:/var/log/rabbitmq/
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit.log
      - TZ=Asia/Taipei
    restart: always

networks:
  rabbitmq:
    driver: bridge